/**
 * @file index.ts
 * @description Type definitions for the Blog application.
 * Defines the core data structures used across the API, hooks, and components.
 */

/**
 * Represents a Blog post entity in the system.
 */
export interface Blog {
    /** Unique identifier for the blog post */
    id: string;
    /** Title of the blog post */
    title: string;
    /** List of categories associated with the blog */
    category: string[];
    /** Short summary or description of the blog */
    description: string;
    /** Publication date of the blog in ISO string format */
    date: string;
    /** URL to the cover image of the blog */
    coverImage: string;
    /** Full content/body of the blog post */
    content: string;
}

/**
 * Represents the data required to create a new Blog post.
 * Omits the 'id' as it is generated by the backend.
 */
export type NewBlog = Omit<Blog, 'id'>;
